I upgraded te MyHDL 0.6 and I had to replace the instance decorator with a simpler version.  Now the sim seems to run fine.  The traceSignals thing doesn't work anymore:
Traceback (most recent call last):
  File "/home/sforman/pypic/sim.py", line 694, in <module>
    ts = traceSignals(main)
  File "/usr/lib/python2.5/site-packages/myhdl/_traceSignals.py", line 77, in __call__
    h = _HierExtr(name, dut, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/myhdl/_extractHierarchy.py", line 176, in __init__
    raise ExtractHierarchyError(_error.InconsistentHierarchy)
ExtractHierarchyError: Inconsistent hierarchy - are all instances returned?

So that sucks.  At least the actual simulation/programmer-circuit-driver
part seems to work fine. Yay!